import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { GalleryComponent } from '../reusable/gallery/gallery.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-cours',
  standalone: true,
  imports: [GalleryComponent, CommonModule],
  templateUrl: './course.component.html',
  styleUrl: './course.component.scss',
})
export class CoursComponent implements OnInit {
  src: string[] = [];
  mainImg: string = '';

  header!: string;
  currDesc: string[] = [];
  path: string[] = [
    'boxing',
    'dance',
    'personal',
    'strength',
    'stretching',
    'yoga',
  ];
  desc: string[] = [
    "Step into the ring and unleash your inner fighter with our invigorating boxing classes. Led by experienced instructors who are passionate about the sport, these classes offer a dynamic blend of cardio, strength, and agility training. Whether you're a seasoned boxer or new to the sport, our classes are designed to accommodate all skill levels and provide a challenging yet rewarding workout experience.\nGain confidence and master the art of boxing as you learn proper techniques and form in a supportive and motivating environment. Our instructors will guide you through a series of drills and exercises, teaching you how to jab, cross, hook, and weave with precision and control. With a focus on technique and safety, you'll develop the skills and confidence to hit harder, move faster, and defend yourself effectively.\nBoxing is not only a great way to improve cardiovascular health and endurance but also to build strength and power throughout the entire body. Through a combination of punching, footwork, and defensive maneuvers, you'll engage multiple muscle groups and torch calories while sculpting lean, toned muscles. Whether you're working the heavy bag, sparring with a partner, or practicing defensive drills, each class will push you to new levels of strength and stamina.\nBeyond the physical benefits, our boxing classes offer a sense of camaraderie and belonging as you join a community of like-minded individuals who share a passion for fitness and self-improvement. Whether you're training for competition or simply looking to challenge yourself in a fun and supportive environment, our boxing classes provide the perfect opportunity to push your limits, break a sweat, and unleash your inner warrior.",
    "Get ready to groove, sweat, and dance your way to fitness with our dynamic dance fitness classes. Led by experienced instructors with a passion for movement and music, these classes are designed to inspire and energize as you let the rhythm of the music move you. Whether you're a seasoned dancer or have two left feet, our classes offer a welcoming and supportive environment where you can let loose and have fun.\nFrom Latin-inspired rhythms to hip-hop beats and everything in between, our dance fitness classes explore a variety of dance styles to keep you motivated and engaged. Whether you're shaking it in a Zumba class, breaking it down in a hip-hop session, or finding your flow in a contemporary dance class, there's something for everyone to enjoy. With a focus on movement, coordination, and expression, you'll improve your dance skills while burning calories and toning muscles.\nDance fitness is not only a great way to improve cardiovascular health and coordination but also to boost your mood and relieve stress. With uplifting music, infectious energy, and easy-to-follow choreography, our classes provide the perfect opportunity to let go of the day's worries and just dance. You'll leave each class feeling invigorated, empowered, and with a smile on your face, ready to take on whatever life throws your way.\nBeyond the physical benefits, our dance fitness classes offer a sense of community and belonging as you join a diverse group of individuals who share a love for movement and music. Whether you're looking to meet new friends, challenge yourself with new dance styles, or simply have a blast on the dance floor, our classes provide a supportive and inclusive environment where you can shine, sweat, and dance your heart out.",
    "Experience the ultimate in personalized fitness with our one-on-one personal training sessions. Whether you're new to exercise, recovering from an injury, or looking to take your fitness to the next level, our certified trainers will create a customized workout plan tailored to your specific goals, abilities, and preferences. From strength training and cardio to flexibility and mobility exercises, each session is designed to maximize your results and optimize your overall health and well-being.\nOur experienced trainers are dedicated to helping you achieve your goals by providing expert guidance, support, and motivation every step of the way. With their knowledge and expertise, they will teach you proper exercise techniques, correct form, and safe practices to ensure you get the most out of your workouts while minimizing the risk of injury. Whether you need a push to go that extra mile or encouragement to overcome obstacles, our trainers will be there to inspire and empower you to reach your full potential.\nOne of the key benefits of personal training is the accountability and progress tracking provided by your dedicated trainer. They will help you set realistic goals, track your progress, and adjust your workout plan as needed to ensure you stay on track and make steady progress towards your objectives. Whether you're aiming to lose weight, build muscle, improve athletic performance, or simply adopt a healthier lifestyle, our trainers will keep you accountable and motivated to stay committed to your fitness journey.\nInvesting in personal training is not just an investment in your physical health, but also in your overall well-being and quality of life. With personalized attention, guidance, and support, you'll not only achieve your fitness goals faster but also develop lifelong habits that will help you maintain your results and enjoy a healthier, happier lifestyle for years to come. So why wait? Take the first step towards a stronger, fitter, and more confident you by booking a personal training session today!",
    "Get ready to power up your workout and unleash your full potential with our strength training classes. Led by experienced instructors who are dedicated to helping you build strength, muscle, and confidence, these classes offer a challenging yet rewarding workout experience. Whether you're a beginner or a seasoned lifter, our classes are designed to accommodate all fitness levels and provide a safe and effective environment for reaching your goals.\nOur strength training classes focus on targeting every major muscle group in the body, from your arms and shoulders to your legs and core. Using a variety of equipment, including free weights, resistance bands, and bodyweight exercises, you'll engage in a series of exercises designed to build strength, improve muscle tone, and increase endurance. With proper form and technique, you'll learn how to safely and effectively challenge your muscles to reach new levels of strength and fitness.\nOne of the key benefits of our strength training classes is the personalized guidance and support provided by our certified trainers. Whether you're looking to increase muscle mass, improve muscular endurance, or enhance athletic performance, our trainers will work with you to develop a customized workout plan tailored to your individual needs and goals. With expert coaching and motivation, you'll push past your limits, break through plateaus, and achieve results you never thought possible.\nBeyond the physical benefits, our strength training classes offer a sense of camaraderie and support as you join a community of like-minded individuals who share a passion for fitness and strength. Whether you're cheering each other on during a challenging set or celebrating a new personal best, our classes provide a supportive and motivating environment where you can push yourself, connect with others, and achieve your fitness goals together.",
    "Discover the benefits of improved flexibility and mobility with our stretching classes. Designed to target tight muscles, release tension, and increase range of motion, these classes offer a rejuvenating and revitalizing experience for both body and mind. Whether you're a fitness enthusiast, athlete, or simply looking to relieve stress and improve overall well-being, our stretching classes provide the perfect opportunity to unwind, relax, and restore balance to your body.\nStretching is not only essential for injury prevention but also for enhancing athletic performance and improving physical function. By incorporating a variety of stretching techniques and exercises into your routine, you'll not only reduce the risk of injury but also optimize muscle function and efficiency, leading to better overall performance in your workouts and daily activities. From dynamic stretching to static holds, our classes will help you unlock your body's full potential and move with ease and grace.\nIn our stretching classes, we emphasize mindful movement and breath awareness to help you deepen your stretch, relax your muscles, and quiet your mind. Through gentle, controlled movements and conscious breathing, you'll learn how to connect with your body, release tension, and promote a sense of calm and relaxation. Whether you're stretching out tight muscles after a tough workout or winding down at the end of a long day, our classes provide a sanctuary for self-care and inner peace.\nBeyond the physical benefits, our stretching classes offer a sense of community and connection as you join a group of like-minded individuals who share a commitment to health and well-being. Whether you're a beginner or experienced practitioner, our classes provide a supportive and inclusive environment where you can explore the benefits of stretching, deepen your practice, and connect with others on a journey towards greater flexibility, mobility, and vitality.",
    "Discover the transformative power of yoga with our invigorating yoga classes. Rooted in ancient tradition yet adapted for modern life, yoga offers a holistic approach to health and wellness, integrating physical postures, breathwork, and mindfulness practices to promote balance, harmony, and inner peace. Whether you're a beginner or experienced practitioner, our classes provide a sanctuary for self-discovery and personal growth, allowing you to reconnect with your body, mind, and spirit.\nYoga is renowned for its ability to improve flexibility, strength, and overall physical fitness. Through a combination of dynamic movements, static holds, and gentle stretches, our classes help you develop greater flexibility, increase muscle tone, and build strength from the inside out. Whether you're working on mastering a challenging pose or exploring the subtleties of alignment, our experienced instructors will guide you safely and effectively towards your goals.\nIn our yoga classes, we emphasize the practice of mindfulness and awareness as a means of cultivating presence, clarity, and inner calm. Through guided meditation, breath awareness, and mindful movement, you'll learn how to quiet the chatter of the mind, let go of stress and tension, and connect with the present moment. Whether you're flowing through a vinyasa sequence or sinking into a restorative pose, our classes provide a sacred space for self-reflection and inner exploration.\nBeyond the physical benefits, our yoga classes offer a sense of community and connection as you join a diverse group of individuals who share a passion for health, wellness, and self-discovery. Whether you're seeking to deepen your practice, meet like-minded souls, or simply find solace in the company of others, our classes provide a supportive and inclusive environment where you can find refuge from the busyness of life and nourish your body, mind, and spirit.",
  ];
  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    const id = this.route.snapshot.params['id'];
    this.header = this.path[id].toUpperCase();
    this.currDesc = this.desc[id].split('\n');
    for (let i = 1; i <= 5; i++) {
      this.src.push('courses/' + this.path[id] + '/' + i + '.jpg');
    }
    this.mainImg='courses/' + this.path[id] + '/' + 0 + '.jpg';
  }
}
